### ISSUE TITLE
Update Faraday Gem in 1.4.X

### ISSUE THREAD

**Issue by andrewhood125** [oauth-xx/oauth2#402] opened 2018-08-14 22:23 UTC
Hi all! 

Would you open to a PR against 1.4.X that bumps the Faraday dependency? I currently need to upgrade our app beyond Faraday 0.13

**Comment by mastermatt** [comment] 2018-08-17 16:42
Duplicate of #373, #378, #382, #384, #385, and #397.
Basically, it's already been updated and will be included in the next release, however, they don't plan on releasing a v1.5 and instead are waiting until v2.0 is ready to go.

**Comment by pboling** [comment] 2018-08-20 00:57
The major version bump is not because we plan to break tons of things internally, though some minor changes might be breaking on some use cases, but rather because faraday releases are essentially unstable, and each minor release is breaking (usually), and as an important dependency we are bumping our major to call out that potential breaking change.

**Comment by pboling** [comment] 2018-08-20 00:59
There is one internal breaking change so far though.  See https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md#unreleased

**Closed** 2018-08-20 01:00 UTC

**Comment by pboling** [comment] 2018-08-20 01:02
Please help us get 2.0 out the door if you have any spare cycles.  None of the core team are feeling much pain, so we are only working on it in our spare time.
