### ISSUE TITLE
Error creation form response hash

### ISSUE THREAD

**Issue by Uko** [oauth-xx/oauth2#147] opened 2013-08-30 13:50 UTC
The response hash from StackOverflow looks like this:

```
{"error_id"=>502,
 "error_name"=>"throttle_violation",
 "error_message"=>"too many requests from this app/user pair, more requests available in 1112 seconds"}
```

OAuth2::Error thinks that responce should have `error` and `error_description` keys.

Can this be tweaked somehow from _oauth-stackoverflow_ gem? Or this should be solved here?

**Comment by josephpage** [comment] 2018-01-04 11:04
As the issue is old and apparently not related to oauth2, I close it.
Feel free to comment or open a new issue if we can help.

**Closed by josephpage** 2018-01-04 11:04 UTC

**Comment by pboling** [comment] 2018-01-04 18:14
A throttle error is the domain of app code, not this gem.  Errors to requests can always be of types other than the one desired, as in this case the error not being oauth compliant, or oauth related even.
